# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(343, 348)
        MainWindow.setStyleSheet("background-color: rgb(132, 132, 132);\n"
"background-color: rgb(113, 113, 113);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(199, 199, 199);\n"
"border-radius: 5px;\n"
"border:1px solid #00000;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(260, 50, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_div.setFont(font)
        self.btn_div.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"border-radius: 10px;\n"
"border:1px solid #862c00;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_div.setObjectName("btn_div")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(100, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_5.setObjectName("btn_5")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_2.setObjectName("btn_2")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(180, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_6.setObjectName("btn_6")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(20, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_4.setObjectName("btn_4")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 50, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_8.setObjectName("btn_8")
        self.btn_c = QtWidgets.QPushButton(self.centralwidget)
        self.btn_c.setGeometry(QtCore.QRect(20, 260, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_c.setFont(font)
        self.btn_c.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius: 10px;\n"
"border:1px solid #9a6700;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_c.setObjectName("btn_c")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(100, 260, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_zero.setFont(font)
        self.btn_zero.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_zero.setObjectName("btn_zero")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(20, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_1.setObjectName("btn_1")
        self.btn_multi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multi.setGeometry(QtCore.QRect(260, 120, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_multi.setFont(font)
        self.btn_multi.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"border-radius: 10px;\n"
"border:1px solid #862c00;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_multi.setObjectName("btn_multi")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(20, 50, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_7.setObjectName("btn_7")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(180, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_3.setObjectName("btn_3")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(180, 260, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius: 10px;\n"
"border:1px solid #9a6700;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(260, 260, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"border-radius: 10px;\n"
"border:1px solid #862c00;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_add.setObjectName("btn_add")
        self.btn_subt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_subt.setGeometry(QtCore.QRect(260, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_subt.setFont(font)
        self.btn_subt.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"border-radius: 10px;\n"
"border:1px solid #862c00;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_subt.setObjectName("btn_subt")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(180, 50, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"border:1px solid #000000;\n"
"QpuchButton: hover(border:#ffff00);")
        self.btn_9.setObjectName("btn_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "0"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_c.setText(_translate("MainWindow", "c"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_multi.setText(_translate("MainWindow", "*"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_subt.setText(_translate("MainWindow", "-"))
        self.btn_9.setText(_translate("MainWindow", "9"))

    def add_function(self):
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))
        self.btn_zero.clicked.connect(lambda: self.write_number(self.btn_zero.text()))
        self.btn_add.clicked.connect(lambda: self.write_number(self.btn_add.text()))
        self.btn_multi.clicked.connect(lambda: self.write_number(self.btn_multi.text()))
        self.btn_div.clicked.connect(lambda: self.write_number(self.btn_div.text()))
        self.btn_subt.clicked.connect(lambda: self.write_number(self.btn_subt.text()))
        self.btn_equal.clicked.connect(self.rezult)
        self.btn_c.clicked.connect(self.clean)

    def write_number(self, number):
        if self.label.text() == "0":
                self.label.setText(number)
        else:
                self.label.setText(self.label.text() + number)
    def rezult(self):
        rez = eval(self.label.text())
        self.label.setText(str(rez))
    def clean(self):
        self.label.setText("0")

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())