# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\raisa\PycharmProjects\OP_R1\garderob.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 395)
        MainWindow.setStyleSheet("QMainWindow {\n"
"\n"
"    background-color: #2b2b2b;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"\n"
"    border: 1px solid #444;\n"
"\n"
"    background-color: #333333;\n"
"\n"
"    border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab {\n"
"\n"
"    background-color: #444;\n"
"\n"
"    color: #bbb;\n"
"\n"
"    padding: 10px 20px;\n"
"\n"
"    border-top-left-radius: 5px;\n"
"\n"
"    border-top-right-radius: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    background-color: #555;\n"
"\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("QTabBar::tab {\n"
"\n"
"    background-color: #444;\n"
"\n"
"    color: #bbb;\n"
"\n"
"    padding: 10px 20px;\n"
"\n"
"    border-top-left-radius: 5px;\n"
"\n"
"    border-top-right-radius: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    background-color: #555;\n"
"\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"")
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.notesEditor = QtWidgets.QTextEdit(self.tab)
        self.notesEditor.setStyleSheet("QTextEdit{\n"
"\n"
"    background-color: #1e1e1e;\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #555;\n"
"\n"
"    border-radius: 3px;\n"
"\n"
"    padding: 5px;\n"
"\n"
"}")
        self.notesEditor.setObjectName("notesEditor")
        self.verticalLayout_2.addWidget(self.notesEditor)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QTabBar::tab {\n"
"\n"
"    background-color: #444;\n"
"\n"
"    color: #bbb;\n"
"\n"
"    padding: 10px 20px;\n"
"\n"
"    border-top-left-radius: 5px;\n"
"\n"
"    border-top-right-radius: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    background-color: #555;\n"
"\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"")
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.taskList = QtWidgets.QListWidget(self.tab_2)
        self.taskList.setStyleSheet("QListWidget{\n"
"\n"
"    background-color: #1e1e1e;\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #555;\n"
"\n"
"    border-radius: 3px;\n"
"\n"
"    padding: 5px;\n"
"\n"
"}")
        self.taskList.setObjectName("taskList")
        self.verticalLayout_4.addWidget(self.taskList)
        self.taskInput = QtWidgets.QLineEdit(self.tab_2)
        self.taskInput.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: #1e1e1e;\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #555;\n"
"\n"
"    border-radius: 3px;\n"
"\n"
"    padding: 5px;\n"
"\n"
"}")
        self.taskInput.setObjectName("taskInput")
        self.verticalLayout_4.addWidget(self.taskInput)
        self.addButton = QtWidgets.QPushButton(self.tab_2)
        self.addButton.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: #007acc;\n"
"\n"
"    color: white;\n"
"\n"
"    border-radius: 3px;\n"
"\n"
"    padding: 5px 15px;\n"
"\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: #0099ff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #005a9e;\n"
"\n"
"}")
        self.addButton.setObjectName("addButton")
        self.verticalLayout_4.addWidget(self.addButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("QTabBar::tab {\n"
"\n"
"    background-color: #444;\n"
"\n"
"    color: #bbb;\n"
"\n"
"    padding: 10px 20px;\n"
"\n"
"    border-top-left-radius: 5px;\n"
"\n"
"    border-top-right-radius: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"\n"
"    background-color: #555;\n"
"\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"")
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.daysList = QtWidgets.QListWidget(self.tab_3)
        self.daysList.setStyleSheet("QListWidget{\n"
"\n"
"    background-color: #1e1e1e;\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #555;\n"
"\n"
"    border-radius: 3px;\n"
"\n"
"    padding: 5px;\n"
"\n"
"}")
        self.daysList.setObjectName("daysList")
        self.horizontalLayout.addWidget(self.daysList)
        self.outfitLabel = QtWidgets.QLabel(self.tab_3)
        self.outfitLabel.setStyleSheet("QLabel#outfitLabel {\n"
"\n"
"    border: 2px dashed #555;\n"
"\n"
"    background-color: #252525;\n"
"\n"
"    color: #888;}")
        self.outfitLabel.setScaledContents(True)
        self.outfitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outfitLabel.setObjectName("outfitLabel")
        self.horizontalLayout.addWidget(self.outfitLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 414, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\raisa\\PycharmProjects\\OP_R1\\images/out.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionClearNotes = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\raisa\\PycharmProjects\\OP_R1\\images/clean.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearNotes.setIcon(icon1)
        self.actionClearNotes.setObjectName("actionClearNotes")
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionClearNotes)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.menubar.triggered['QAction*'].connect(MainWindow.close) # type: ignore
        self.menubar.triggered['QAction*'].connect(self.notesEditor.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        days = ["Понеділок", "Вівторок", "Середа", "Четвер", "П'ятниця", "Субота", "Неділя"]
        self.daysList.addItems(days)

        # 2. Підключення сигналів кнопок
        self.addButton.clicked.connect(self.add_task)

        # 3. Підключення сигналу зміни елемента списку
        self.daysList.currentRowChanged.connect(self.show_outfit)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student_WorkSpace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Нотатки"))
        self.addButton.setText(_translate("MainWindow", "ДОДАТИ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Справи"))
        self.outfitLabel.setText(_translate("MainWindow", "ФОТО КАПСУЛИ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Гардероб"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Правка"))
        self.actionExit.setText(_translate("MainWindow", "Вийти"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionClearNotes.setText(_translate("MainWindow", "Очистити нотатки"))
        self.actionClearNotes.setShortcut(_translate("MainWindow", "Ctrl+Del"))

    def add_task(self):
        task_text = self.taskInput.text()
        if task_text:
            self.tasksList.addItem(task_text)
            self.taskInput.clear()

    def show_outfit(self, row):

        # row - індекс дня (0-6)
        # Шлях до картинки має відповідати індексу (наприклад: 0.png)
        # Переконайтеся, що папка 'images' існує поруч із main.py
        image_path = f"images/{row}.jpg"
        pixmap = QPixmap(image_path)
        if not pixmap.isNull():
            self.outfitLabel.setPixmap(pixmap)
        else:
            self.outfitLabel.setText("Картинку не знайдено")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
