# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\star_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 254)
        MainWindow.setStyleSheet("background-color: #02050a; \n"
"border: 5px double #1e272e;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dial_speed = QtWidgets.QDial(self.centralwidget)
        self.dial_speed.setGeometry(QtCore.QRect(120, 60, 121, 81))
        self.dial_speed.setStyleSheet("background-color: #0f172a;\n"
"border: 2px solid #3b82f6;")
        self.dial_speed.setObjectName("dial_speed")
        self.lcd_speed = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_speed.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.lcd_speed.setStyleSheet("color: #38bdf8; \n"
"background-color: #082f49; \n"
"border: 2px solid #38bdf8; \n"
"border-radius: 8px;\n"
"")
        self.lcd_speed.setObjectName("lcd_speed")
        self.progress_fuel = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_fuel.setGeometry(QtCore.QRect(247, 10, 111, 31))
        self.progress_fuel.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #1e293b;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    color: transparent; /* Ховаємо відсотки для краси */\n"
"    background-color: #0f172a;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #7c3aed, stop:1 #3b82f6);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.progress_fuel.setProperty("value", 24)
        self.progress_fuel.setObjectName("progress_fuel")
        self.btn_jump = QtWidgets.QPushButton(self.centralwidget)
        self.btn_jump.setGeometry(QtCore.QRect(80, 160, 211, 31))
        self.btn_jump.setStyleSheet("QPushButton {\n"
"    background-color: #1e1b4b;\n"
"    color: #f43f5e;\n"
"    border: 3px solid #f43f5e;\n"
"    border-radius: 15px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover { background-color: #f43f5e; color: white; }\n"
"")
        self.btn_jump.setObjectName("btn_jump")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(60, 200, 251, 41))
        self.label_status.setStyleSheet("QLabel {\n"
"    color: #94a3b8;\n"
"    font-family: \'Consolas\';\n"
"    font-size: 16px;\n"
"    background-color: #1e293b;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.label_status.setObjectName("label_status")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.dial_speed.valueChanged['int'].connect(self.lcd_speed.display) # type: ignore
        self.dial_speed.valueChanged['int'].connect(self.progress_fuel.setValue) # type: ignore
        self.btn_jump.clicked.connect(self.label_status.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_jump.setText(_translate("MainWindow", "СТРИБОК У ГІПЕРПРОСТІР"))
        self.label_status.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
