# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(309, 529)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.btn_backspace = QtWidgets.QPushButton(self.centralwidget)
        self.btn_backspace.setGeometry(QtCore.QRect(20, 380, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_backspace.setFont(font)
        self.btn_backspace.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(188, 188, 188);\n"
"border-radius: 30px;")
        self.btn_backspace.setObjectName("btn_backspace")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(20, 170, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_7.setObjectName("btn_7")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(20, 240, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_4.setObjectName("btn_4")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(20, 310, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_1.setObjectName("btn_1")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(90, 380, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_0.setFont(font)
        self.btn_0.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_0.setObjectName("btn_0")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(90, 170, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_8.setObjectName("btn_8")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(160, 380, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(188, 188, 188);\n"
"border-radius: 30px;")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(90, 310, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_2.setObjectName("btn_2")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(90, 240, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_5.setObjectName("btn_5")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(160, 170, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_9.setObjectName("btn_9")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(160, 310, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_3.setObjectName("btn_3")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(160, 240, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(144, 144, 144);\n"
"border-radius: 30px;")
        self.btn_6.setObjectName("btn_6")
        self.btn_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multiply.setGeometry(QtCore.QRect(230, 170, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn_multiply.setFont(font)
        self.btn_multiply.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 30px;")
        self.btn_multiply.setObjectName("btn_multiply")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(230, 310, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 30px;\n"
"")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(230, 240, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 30px;")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_divide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divide.setGeometry(QtCore.QRect(230, 380, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn_divide.setFont(font)
        self.btn_divide.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(255, 170, 0);\n"
"border-radius: 30px;")
        self.btn_divide.setObjectName("btn_divide")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(20, 450, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 30px;")
        self.btn_equal.setObjectName("btn_equal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 309, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "0"))
        self.btn_backspace.setText(_translate("MainWindow", "⌫"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_multiply.setText(_translate("MainWindow", "ⅹ"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_divide.setText(_translate("MainWindow", "÷"))
        self.btn_equal.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
