# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\dresser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 490)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #2b2b2b;\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    background-color: rgb(98, 98, 98);\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #444;\n"
"    color: #bbb;\n"
"    padding: 5px 20px;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #555;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"QTextEdit, QListWidget, QLineEdit {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #007acc;\n"
"    color: white;\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0099ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #005a9e;\n"
"}\n"
"\n"
"QLabel#outfitLabel {\n"
"    border: 2px dashed #555;\n"
"    background-color: #252525;\n"
"    color: #888;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setDocumentMode(False)
        self.tabs.setTabsClosable(False)
        self.tabs.setObjectName("tabs")
        self.notes_tab = QtWidgets.QWidget()
        self.notes_tab.setObjectName("notes_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.notes_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.notesEdotior = QtWidgets.QTextEdit(self.notes_tab)
        self.notesEdotior.setObjectName("notesEdotior")
        self.horizontalLayout.addWidget(self.notesEdotior)
        self.tabs.addTab(self.notes_tab, "")
        self.tasks_tab = QtWidgets.QWidget()
        self.tasks_tab.setObjectName("tasks_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tasks_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.taskInput = QtWidgets.QLineEdit(self.tasks_tab)
        self.taskInput.setObjectName("taskInput")
        self.verticalLayout_3.addWidget(self.taskInput)
        self.addButton = QtWidgets.QPushButton(self.tasks_tab)
        self.addButton.setObjectName("addButton")
        self.verticalLayout_3.addWidget(self.addButton)
        self.tasksList = QtWidgets.QListWidget(self.tasks_tab)
        self.tasksList.setObjectName("tasksList")
        self.verticalLayout_3.addWidget(self.tasksList)
        self.tabs.addTab(self.tasks_tab, "")
        self.dresser_tab = QtWidgets.QWidget()
        self.dresser_tab.setObjectName("dresser_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dresser_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.daysList = QtWidgets.QListWidget(self.dresser_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daysList.sizePolicy().hasHeightForWidth())
        self.daysList.setSizePolicy(sizePolicy)
        self.daysList.setObjectName("daysList")
        self.horizontalLayout_2.addWidget(self.daysList)
        self.outfitLabel = QtWidgets.QLabel(self.dresser_tab)
        self.outfitLabel.setEnabled(True)
        self.outfitLabel.setScaledContents(False)
        self.outfitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outfitLabel.setObjectName("outfitLabel")
        self.horizontalLayout_2.addWidget(self.outfitLabel)
        self.tabs.addTab(self.dresser_tab, "")
        self.verticalLayout.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 548, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actionClear)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(2)
        self.actionExit.triggered.connect(MainWindow.close) # type: ignore
        self.actionClear.triggered.connect(self.notesEdotior.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabs.setTabText(self.tabs.indexOf(self.notes_tab), _translate("MainWindow", "Нотатки"))
        self.addButton.setText(_translate("MainWindow", "PushButton"))
        self.tabs.setTabText(self.tabs.indexOf(self.tasks_tab), _translate("MainWindow", "Справи"))
        self.outfitLabel.setText(_translate("MainWindow", "TextLabel"))
        self.tabs.setTabText(self.tabs.indexOf(self.dresser_tab), _translate("MainWindow", "Гардероб"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Правка"))
        self.action.setText(_translate("MainWindow", "Правка"))
        self.actionExit.setText(_translate("MainWindow", "Вихід"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionClear.setText(_translate("MainWindow", "Очистити нотатки"))
        self.actionClear.setShortcut(_translate("MainWindow", "Ctrl+Del"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
